### ISSUE TITLE
comune di prato

### ISSUE THREAD

**Issue by giorgialodi** [italia/public-opendata-sources#2]
Comune di Prato is already harvested by Regione Toscana (whose, BTW, endpoint DCAT-AP_IT is now available online again). 

Therefore, what we can do can be the following alternative actions:

1) we harvest Toscana via CKAN for DCATAPIT and we exclude Prato in the configuration; then we harvest Prato separately
2) we harvest Toscana via endpoint dcat-ap_it or CKAN  for DCATAPIT and we delete Prato that won't be separately harvested

In the guidelines we recommend the second solution since it is easier controlling the harvesting process from the central viewpoint in the case of regions which aggregate data for their municipalities. The drawback is that since we do not have a specific facet menu for the rightsHolder field of DCAT-AP_IT, all datasets are assigned to Regione Toscana organization (while in the first solution above we may have an entry in the organization menu dedicated to Comune di Prato).
In any case, with solution 2 if rightsHolder is correctly materialized in the metadata, this is displayed in the landing page of the dataset.

**Comment by jenkin** [comment]
I removed the source related to Comune di Prato and update [harvest type for Regione Toscana](https://github.com/italia/public-opendata-sources/blob/master/sources/catalogo-open-data-regione-toscana.json). Comune di Prato is [still there as organization](https://github.com/italia/public-opendata-sources/blob/master/orgs/comune-di-prato.json).
