### ISSUE TITLE
Add informations about source types

### ISSUE THREAD

**Issue by jenkin** [italia/public-opendata-sources#5]
Following [source schema](https://github.com/italia/public-opendata-sources/blob/master/schemas/sources.schema.json#L46), `source_type` is an enum fields.

```
"source_type": {
    "type": "string",
    "description": "Identifier of harvest type.",
    "enum": [
        "ckan",
        "multilang",
        "dcat_rdf",
        "dcat_json",
        "CKAN-DCATAPIT",
        "DCAT_AP-IT CSW Harvester"
    ]
}
```

We need a detailed explanation of each value in documentation, with some examples.

**Comment by giorgialodi** [comment]
ok let's write a small paragraph to be included in the readme where we explain each item. Multilang sounds strange to me anyway

**Comment by jenkin** [comment]
Yep, see #8

**Comment by giorgialodi** [comment]
@jenkin "multilang" (second item) does not make sense. It is CSW server (multilang).

**Comment by jenkin** [comment]
@giorgialodi When you add a harvest source, CKAN-IT interface offers these radio buttons.

![Screenshot_20191113_105221](https://user-images.githubusercontent.com/426495/68752493-b3d57200-0603-11ea-9420-7b2c7e514a36.png)

Following table summarizes available labels and values from those radio buttons.

Label | Value
------------ | -------------
CKAN | `ckan`
CSW server (Multilang) | `multilang`
Generic DCAT RDF Harvester | `dcat_rdf`
DCAT JSON Harvester | `dcat_json`
CKAN harvester for DCATAPIT | `CKAN-DCATAPIT`
DCAT_AP-IT CSW Harvester | `DCAT_AP-IT CSW Harvester`

Our `source_type` can be one of the previous values, not labels.

**Comment by jenkin** [comment]
Fixed in https://github.com/italia/public-opendata-sources/pull/14
